[tool.poetry]
name = "phoney"
version = "0.1.0"
description = "Test data generator API"
authors = ["JP White <jpwhite3@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
bcrypt = "^3.2.0"
fastapi = "^0.65.2"
uvicorn = "^0.13.4"
passlib = "^1.7.4"
PyJWT = "^2.4.0"
python-dotenv = "^0.17.1"
python-multipart = "^0.0.5"
Faker = "^8.8.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
black = "^21.5b1"
flake8 = "^3.9.2"
coverage = "^5.5"
pytest-cov = "^2.12.0"
coveralls = "^3.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
